import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

const repoRoot = process.cwd();

function read(relativePath) {
  return fs.readFileSync(path.join(repoRoot, relativePath), "utf8");
}

test("public data hub consumes runtime public authority exports", () => {
  const source = read("js/public-data-hub.js");
  assert.match(source, /publicAuthorityIdentities:\s*\["\/shared\/state\/public_identities\.json", "\/runtime\/exports\/public_identities\.json"\]/);
  assert.match(source, /publicAuthorityArtifacts:\s*\["\/shared\/state\/public_artifacts\.json", "\/runtime\/exports\/public_artifacts\.json"\]/);
  assert.match(source, /buildPublicAuthorityIdentityMap/);
  assert.match(source, /accountUserCode:\s*normalizeAuthorityKey\(raw\.user_code \|\| raw\.canonical_user_code \|\| raw\.account_user_code\)/);
  assert.match(source, /publicIdentityCode:/);
  assert.match(source, /authority:\s*\{/);
});

test("public app wires authority request submission and my-data history to the real endpoints", () => {
  const source = read("js/public-pages-app.js");
  assert.match(source, /AUTH_PUBLIC_AUTHORITY_REQUESTS_URL = `\$\{AUTH_API_BASE\}\/api\/public\/authority\/requests`/);
  assert.match(source, /AUTH_PUBLIC_AUTHORITY_REQUESTS_MINE_URL = `\$\{AUTH_API_BASE\}\/api\/public\/authority\/requests\/mine`/);
  assert.match(source, /AUTH_PUBLIC_PROGRESSION_ME_URL = `\$\{AUTH_API_BASE\}\/api\/public\/progression\/me`/);
  assert.match(source, /AUTH_PUBLIC_ECONOMY_ME_URL = `\$\{AUTH_API_BASE\}\/api\/public\/economy\/me`/);
  assert.match(source, /AUTH_PUBLIC_ECONOMY_EXCHANGE_URL = `\$\{AUTH_API_BASE\}\/api\/public\/economy\/me\/exchange`/);
  assert.match(source, /submitPublicAuthorityRequest/);
  assert.match(source, /fetchMyPublicAuthorityRequests/);
  assert.match(source, /fetchMyPublicProgression/);
  assert.match(source, /fetchMyPublicEconomy/);
  assert.match(source, /exchangeMyPublicValueItem/);
  assert.match(source, /summary\.xp_total \?\? summary\.total_xp/);
  assert.match(source, /PUBLIC_XP_ICON_PATH = "\/assets\/games\/xpstar\.webp"/);
  assert.match(source, /function buildProgressionLevelChip/);
  assert.match(source, /function formatOrdinal\(value\)/);
  assert.match(source, /mod100 >= 11 && mod100 <= 13/);
  assert.match(source, /\{ 1: "st", 2: "nd", 3: "rd" \}\[parsed % 10\] \|\| "th"/);
  assert.match(source, /function progressionGlobalPlacementRank\(summary = \{\}\)/);
  assert.match(source, /function buildProgressionGlobalRankValue\(summary = \{\}, options = \{\}\)/);
  assert.match(source, /chip\.append\(icon, create\("span", "", presentation\.label\)\)/);
  assert.doesNotMatch(source, /`Level \$\{presentation\.label\}`/);
  assert.match(source, /event\?\.source_domain/);
  assert.match(source, /buildAuthorityRequestPanel/);
  assert.match(source, /resolveProfileAuthorityContext/);
  assert.match(source, /renderCommunityMyData/);
  assert.match(source, /Public progression/);
  assert.match(source, /Recent XP events/);
  assert.match(source, /Public economy and inventory/);
  assert.match(source, /Recent economy history/);
  assert.match(source, /Pending review/);
  assert.match(source, /openAuthModal:\s*ctx\.openAuthModal/);
});

test("public leaderboards route hydrates from authoritative progression API", () => {
  const app = read("js/public-pages-app.js");
  const css = read("css/public-shell.css");
  assert.match(app, /AUTH_PUBLIC_PROGRESSION_LEADERBOARD_URL = `\$\{AUTH_API_BASE\}\/api\/public\/progression\/leaderboard`/);
  assert.match(app, /fetchPublicProgressionLeaderboard/);
  assert.match(app, /renderLeaderboards/);
  assert.doesNotMatch(app, /renderLeaderboardsPlaceholder/);
  assert.match(app, /Global public progression ranked from authoritative XP totals/);
  assert.match(app, /entry\?\.xp_total \?\? entry\?\.total_xp/);
  assert.match(app, /buildProgressionXpValue\(leaderboardXpTotal\(entry\), \{ compact: true \}\)/);
  assert.match(app, /placement_rank \|\| entry\?\.rank \|\| entry\?\.position/);
  assert.match(app, /buildProgressionLevelChip\(entry, \{ compact: true \}\)/);
  assert.match(app, /payload\?\.canonical_user_code/);
  assert.match(app, /authorityIdentity\?\.account_user_code/);
  assert.match(app, /function leaderboardHandle\(identity = \{\}\)/);
  assert.match(app, /identity\.public_slug[\s\S]*identity\.profile_slug[\s\S]*profileUrlSlug/);
  assert.doesNotMatch(app.match(/function leaderboardHandle\(identity = \{\}\) \{[\s\S]*?return "";\n  \}/)?.[0] || "", /identity\.user_code/);
  assert.match(app, /return `@\$\{handle\}`/);
  assert.match(app, /fallback_public_identity_code/);
  assert.match(app, /function leaderboardProfileHref\(entry = \{\}\)/);
  assert.match(app, /const link = create\("a", "dashboard-action progression-leaderboard-profile-link", "View profile"\)/);
  assert.match(app, /function buildLeaderboardDetail\(entry = \{\}\)/);
  assert.match(app, /toggle\.setAttribute\("aria-expanded", isExpanded \? "true" : "false"\)/);
  assert.match(app, /function toggleLeaderboardRow\(entry = \{\}, state = \{\}, isExpanded = false\)/);
  assert.match(app, /row\.addEventListener\("keydown"/);
  assert.match(app, /event\.key !== "Enter" && event\.key !== " "/);
  assert.match(app, /event\.stopPropagation\(\)/);
  assert.match(app, /function filterLeaderboardRows\(rows = \[\], query = ""\)/);
  assert.match(app, /Search by name, @handle, level, or badge/);
  assert.match(app, /progressionLevelPresentation\(entry\)/);
  assert.match(app, /addStat\("Rank", `#\$\{formatNumber/);
  assert.match(app, /stats\.appendChild\(buildLeaderboardLevelCard\(entry\)\)/);
  assert.match(app, /applyProfileCurrentLevelCardTheme\(item, entry\)/);
  assert.doesNotMatch(app, /addStat\("Rank", level\.label/);
  assert.match(app, /LEADERBOARD_PLACEMENT_ASSETS = Object\.freeze/);
  assert.match(app, /1: "\/assets\/games\/lb-first\.webp"/);
  assert.match(app, /2: "\/assets\/games\/lb-second\.webp"/);
  assert.match(app, /3: "\/assets\/games\/lb-third\.webp"/);
  assert.match(app, /function computeLeaderboardTiePlacements\(rows = \[\]\)/);
  assert.match(app, /currentPlacement = index \+ 1/);
  assert.match(app, /tie_placement_rank: currentPlacement/);
  assert.match(css, /\.progression-leaderboard-row/);
  assert.match(css, /\.progression-leaderboard-row--top-1/);
  assert.match(css, /\.progression-leaderboard-medallion/);
  assert.match(css, /\.progression-leaderboard-level-card/);
  assert.match(css, /\.progression-board\.dashboard-card/);
  assert.match(css, /\.progression-leaderboard-detail/);
  assert.match(css, /\.progression-leaderboard-search input/);
  assert.match(css, /\.progression-level-chip/);
  assert.match(css, /\.progression-xp-icon/);
});

test("public profile game section renders runtime progression and economy authority summaries", () => {
  const app = read("js/public-pages-app.js");
  const css = read("css/public-shell.css");
  const profileSection = app.match(/function buildProfileGameCompetitionSection\(profile = null, options = \{\}\) \{[\s\S]*?return details;\n  \}/)?.[0] || "";
  assert.ok(profileSection, "profile progression section should exist");
  assert.match(app, /payload\?\.progression && typeof payload\.progression === "object"/);
  assert.match(app, /payload\?\.economy && typeof payload\.economy === "object"/);
  assert.match(app, /Array\.isArray\(payload\?\.inventory\)/);
  assert.match(app, /ECONOMY_CURRENCY_SYMBOL_PATH = "\/assets\/games\/currencyunit\.svg"/);
  assert.match(app, /function buildEconomyDenominationBreakdown\(wallet = \{\}\)/);
  assert.match(app, /function buildEconomyBreakdownList\(rows = \[\], emptyText = "No entries available yet\.", className = ""\)/);
  assert.match(app, /wallet\.denomination_breakdown\.filter/);
  assert.match(app, /item\?\.should_display \|\| item\?\.always_show_in_balance \|\| Number\(item\?\.count \|\| 0\) > 0/);
  assert.match(app, /icon\.style\.setProperty\("--economy-currency-symbol"/);
  assert.match(app, /fullColorIcon/);
  assert.match(profileSection, /progression\.xp_total \?\? progression\.total_xp/);
  assert.match(profileSection, /buildEconomyBalanceValue\(economy \|\| \{\}, \{ prominent: true, fullColorIcon: true \}\)/);
  assert.match(profileSection, /buildEconomyDenominationBreakdown\(economy \|\| \{\}\)/);
  assert.match(profileSection, /buildInventorySummaryList\(displayInventory\)/);
  assert.match(profileSection, /buildPublicValueItemExchangePanel\(exchangeableItems\)/);
  assert.match(profileSection, /options\.canEdit/);
  assert.match(profileSection, /buildProgressionXpValue\(xpTotal, \{ prominent: true \}\)/);
  assert.match(profileSection, /buildProgressionLevelChip\(progression, \{ prominent: true \}\)/);
  assert.match(app, /function publicLevelBannerImagePath\(presentation = \{\}\)/);
  assert.match(app, /PUBLIC_LEVEL_BANNER_ASSET_SLUGS = new Set/);
  assert.match(app, /\/assets\/backgrounds\/lvlbanner-\$\{slug\}\.webp/);
  assert.match(profileSection, /profile-game-preview-card--featured profile-game-preview-card--current-level/);
  assert.match(profileSection, /applyProfileCurrentLevelCardTheme\(card, progression\)/);
  assert.match(profileSection, /label: "Current XP \/ Global rank"/);
  assert.match(profileSection, /buildProgressionGlobalRankValue\(progression, \{ prominent: true, emptyLabel: "Unranked" \}\)/);
  assert.match(profileSection, /LEADERBOARD_PLACEMENT_ASSETS\[placementRank\]/);
  assert.match(profileSection, /Leaderboard placement is separate from/);
  assert.match(profileSection, /No global leaderboard placement has been returned for this identity yet/);
  assert.match(profileSection, /profile-game-preview-card--featured/);
  assert.match(profileSection, /profile-game-progress-meter/);
  assert.match(profileSection, /No level yet/);
  assert.doesNotMatch(profileSection, /value: progression \? buildProgressionRankChip\(progression, \{ compact: true \}\) : "Bronze"/);
  assert.match(profileSection, /XP, level, wallet balance, and inventory hydrate from runtime public authority/);
  assert.match(css, /\.progression-xp-value--prominent/);
  assert.match(css, /\.progression-global-rank-value--prominent/);
  assert.match(css, /\.economy-balance-value--prominent/);
  assert.match(css, /\.economy-balance-icon--full-color/);
  assert.match(css, /\.profile-game-xp-rank-combo--top-1/);
  assert.match(css, /\.profile-game-xp-rank-combo--top-2/);
  assert.match(css, /\.profile-game-xp-rank-combo--top-3/);
  assert.match(css, /\.profile-game-xp-rank-placement-icon/);
  assert.match(app, /1: "\/assets\/games\/lb-first\.webp"/);
  assert.match(app, /2: "\/assets\/games\/lb-second\.webp"/);
  assert.match(app, /3: "\/assets\/games\/lb-third\.webp"/);
  assert.match(css, /\.progression-level-chip--prominent/);
  assert.match(css, /\.profile-game-preview-card--featured/);
  assert.match(css, /\.profile-game-preview-card--current-level/);
  assert.match(css, /--profile-current-level-color/);
  assert.match(css, /--profile-current-level-banner-image/);
  assert.match(css, /\.profile-game-preview-card--current-level::before\s*\{[\s\S]*mask-image:\s*linear-gradient/);
  assert.match(css, /\.profile-game-preview-card--current-level\.has-level-banner::before\s*\{[\s\S]*opacity:\s*0\.62/);
  assert.match(css, /\.profile-game-preview-card--breakdown,[\s\S]*\.profile-game-preview-card--progress\s*\{[\s\S]*grid-column:\s*span 3/);
  assert.match(profileSection, /profile-game-preview-card--breakdown profile-game-preview-card--balance/);
  assert.match(profileSection, /profile-game-preview-card--breakdown profile-game-preview-card--inventory/);
  assert.match(css, /\.profile-game-inventory-stack/);
  assert.match(app, /buildProfileGameCompetitionSection\(profile, \{ canEdit \}\)/);
});

test("public profile overview table uses the same runtime progression summary as games", () => {
  const app = read("js/public-pages-app.js");
  const overviewSection = app.match(/function buildProfileOverviewPanel\(profile, artifacts, helpers\) \{[\s\S]*?return section;\n  \}/)?.[0] || "";
  assert.ok(overviewSection, "profile overview section should exist");
  assert.match(overviewSection, /const progression = profile\?\.progression && typeof profile\.progression === "object" \? profile\.progression : null/);
  assert.match(overviewSection, /const economy = profile\?\.economy && typeof profile\.economy === "object" \? profile\.economy : null/);
  assert.match(overviewSection, /progression\.xp_total \?\? progression\.total_xp \?\? 0/);
  assert.match(overviewSection, /buildProgressionXpValue\(progression\.xp_total \?\? progression\.total_xp \?\? 0, \{ compact: true \}\)/);
  assert.match(overviewSection, /buildProgressionLevelChip\(progression, \{ compact: true \}\)/);
  assert.match(overviewSection, /buildProgressionGlobalRankValue\(progression, \{ compact: true, emptyLabel: "Unranked" \}\)/);
  assert.match(overviewSection, /addRow\("XP", overviewXpValue, !progression\)/);
  assert.match(overviewSection, /addRow\("Level", overviewLevelValue, !progression\)/);
  assert.match(overviewSection, /addRow\("Global Rank", overviewGlobalRankValue, !progression\)/);
  assert.match(overviewSection, /addRow\("Balance", economy \? buildEconomyBalanceValue\(economy, \{ compact: true \}\) : "Starting", false\)/);
  assert.match(overviewSection, /addRow\("Inventory", displayInventory\.length \? `\$\{formatNumber\(displayInventory\.length\)\} item type/);
  assert.doesNotMatch(overviewSection, /addRow\("XP", "Pending", true\)/);
  assert.doesNotMatch(overviewSection, /addRow\("Rank", "Pending", true\)/);
});

test("public level chips include restrained hover sheen without changing compact consumers", () => {
  const css = read("css/public-shell.css");

  assert.match(css, /\.progression-level-chip::before,[\s\S]*\.progression-rank-chip::before\s*\{/);
  assert.match(css, /\.progression-level-chip:hover::before,[\s\S]*\.progression-rank-chip:focus-visible::before\s*\{[\s\S]*animation:\s*progression-rank-chip-sheen 3\.2s/);
  assert.match(css, /@keyframes progression-rank-chip-sheen/);
  assert.match(css, /prefers-reduced-motion:\s*reduce[\s\S]*\.progression-rank-chip::before/);
  assert.match(css, /\.progression-level-chip--compact,[\s\S]*\.economy-balance-value--compact\s*\{[\s\S]*font-size:\s*12px/);
  assert.match(css, /\.progression-level-chip--compact \.progression-level-chip-icon,[\s\S]*\.economy-balance-value--compact \.economy-balance-icon\s*\{[\s\S]*width:\s*16px/);
  assert.match(css, /\.economy-balance-icon\s*\{[\s\S]*mask:\s*var\(--economy-currency-symbol\) center \/ contain no-repeat/);
  assert.match(css, /\.economy-denomination-breakdown\s*\{/);
  assert.match(css, /\.economy-breakdown-icon,[\s\S]*\.economy-denomination-chip img,[\s\S]*\.inventory-summary-icon\s*\{[\s\S]*object-fit:\s*contain/);
});

test("public economy rendering keeps denominations separate from inventory rows", () => {
  const app = read("js/public-pages-app.js");
  const css = read("css/public-shell.css");

  assert.match(app, /currency_unit_label \|\| "Credit"/);
  assert.match(app, /currency_unit_plural_label \|\| `\$\{singular\}s`/);
  assert.match(app, /walletOrValue\.balance_total_credits \?\? walletOrValue\.balance_current/);
  assert.match(app, /walletCard\.appendChild\(buildEconomyDenominationBreakdown\(wallet\)\)/);
  assert.match(app, /icon\.src = economyAssetPath\("\/assets\/games\/sscurrency\.webp"\)/);
  assert.match(app, /function isWalletDenominationInventoryItem\(item = \{\}\)/);
  assert.match(app, /\["currency\.coin", "currency\.bank_token"\]\.includes\(itemCode\)/);
  assert.doesNotMatch(app, /metadata\.system_asset_type === "economy_denomination"/);
  assert.match(app, /return Number\(item\?\.quantity \|\| 0\) > 0 && !isWalletDenominationInventoryItem\(item\)/);
  assert.match(app, /const displayInventory = inventory\.filter\(\(item\) => !isWalletDenominationInventoryItem\(item\)\)/);
  assert.match(app, /"currency\.gem\.green"/);
  assert.match(app, /"currency\.gem\.red"/);
  assert.match(app, /"currency\.gem\.blue"/);
  assert.match(app, /"currency\.diamond"/);
  assert.match(app, /className: "inventory-summary-row"/);
  assert.match(app, /quantityPrefix: "x"/);
  assert.match(app, /row\.append\(icon, body, create\("strong", "economy-breakdown-quantity", `\$\{entry\.quantityPrefix \|\| ""\}\$\{formatNumber\(entry\.quantity \|\| 0\)\}`\)\)/);
  assert.match(app, /const exchangePanel = buildPublicValueItemExchangePanel\(exchangeableItems\)/);
  assert.match(app, /Gems and diamonds cannot be purchased directly/);
  assert.match(app, /body: JSON\.stringify\(\{[\s\S]*item_code: itemCode,[\s\S]*quantity,[\s\S]*reason_text: reasonText/);
  assert.match(css, /\.economy-breakdown-row,[\s\S]*\.economy-denomination-chip,[\s\S]*\.inventory-summary-row\s*\{[\s\S]*grid-template-columns:\s*24px minmax\(0, 1fr\) auto/);
  assert.match(css, /\.economy-breakdown-icon,[\s\S]*\.economy-denomination-chip img,[\s\S]*\.inventory-summary-icon\s*\{[\s\S]*width:\s*24px/);
});

test("public profile progress meter uses animated electric blue fill", () => {
  const app = read("js/public-pages-app.js");
  const css = read("css/public-shell.css");

  assert.match(app, /fill\.style\.setProperty\("--profile-progress-target", `\$\{progressPercent\}%`\)/);
  assert.match(app, /profile-game-progress-meter profile-game-progress-meter--animated/);
  assert.match(app, /profile-game-progress-meter-fill profile-game-progress-meter-fill--electric/);
  assert.match(css, /\.profile-game-progress-meter-fill\s*\{[\s\S]*linear-gradient\(90deg, #0487ff 0%, #18c3ff 52%, #78ecff 100%\)/);
  assert.match(css, /animation:\s*profile-game-progress-fill 820ms/);
  assert.match(css, /\.profile-game-preview-card--progress:hover \.profile-game-progress-meter-fill\s*\{[\s\S]*animation:\s*profile-game-progress-refill 620ms/);
  assert.match(css, /@keyframes profile-game-progress-fill/);
  assert.match(css, /@keyframes profile-game-progress-refill/);
  assert.match(css, /prefers-reduced-motion:\s*reduce[\s\S]*profile-game-progress-meter-fill/);
});
