import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

const repoRoot = process.cwd();

function read(relativePath) {
  return fs.readFileSync(path.join(repoRoot, relativePath), "utf8");
}

test("public data hub consumes runtime public authority exports", () => {
  const source = read("js/public-data-hub.js");
  assert.match(source, /publicAuthorityIdentities:\s*\["\/shared\/state\/public_identities\.json", "\/runtime\/exports\/public_identities\.json"\]/);
  assert.match(source, /publicAuthorityArtifacts:\s*\["\/shared\/state\/public_artifacts\.json", "\/runtime\/exports\/public_artifacts\.json"\]/);
  assert.match(source, /buildPublicAuthorityIdentityMap/);
  assert.match(source, /accountUserCode:\s*normalizeAuthorityKey\(raw\.user_code \|\| raw\.canonical_user_code \|\| raw\.account_user_code\)/);
  assert.match(source, /publicIdentityCode:/);
  assert.match(source, /authority:\s*\{/);
});

test("public app wires authority request submission and my-data history to the real endpoints", () => {
  const source = read("js/public-pages-app.js");
  assert.match(source, /AUTH_PUBLIC_AUTHORITY_REQUESTS_URL = `\$\{AUTH_API_BASE\}\/api\/public\/authority\/requests`/);
  assert.match(source, /AUTH_PUBLIC_AUTHORITY_REQUESTS_MINE_URL = `\$\{AUTH_API_BASE\}\/api\/public\/authority\/requests\/mine`/);
  assert.match(source, /AUTH_PUBLIC_PROGRESSION_ME_URL = `\$\{AUTH_API_BASE\}\/api\/public\/progression\/me`/);
  assert.match(source, /AUTH_PUBLIC_ECONOMY_ME_URL = `\$\{AUTH_API_BASE\}\/api\/public\/economy\/me`/);
  assert.match(source, /AUTH_PUBLIC_ECONOMY_EXCHANGE_URL = `\$\{AUTH_API_BASE\}\/api\/public\/economy\/me\/exchange`/);
  assert.match(source, /submitPublicAuthorityRequest/);
  assert.match(source, /fetchMyPublicAuthorityRequests/);
  assert.match(source, /fetchMyPublicProgression/);
  assert.match(source, /fetchMyPublicEconomy/);
  assert.match(source, /exchangeMyPublicValueItem/);
  assert.match(source, /summary\.xp_total \?\? summary\.total_xp/);
  assert.match(source, /PUBLIC_XP_ICON_PATH = "\/assets\/games\/xpstar\.webp"/);
  assert.match(source, /function buildProgressionLevelChip/);
  assert.match(source, /function formatOrdinal\(value\)/);
  assert.match(source, /mod100 >= 11 && mod100 <= 13/);
  assert.match(source, /\{ 1: "st", 2: "nd", 3: "rd" \}\[parsed % 10\] \|\| "th"/);
  assert.match(source, /function progressionGlobalPlacementRank\(summary = \{\}\)/);
  assert.match(source, /function buildProgressionGlobalRankValue\(summary = \{\}, options = \{\}\)/);
  assert.match(source, /chip\.append\(icon, create\("span", "", presentation\.label\)\)/);
  assert.doesNotMatch(source, /`Level \$\{presentation\.label\}`/);
  assert.match(source, /event\?\.source_domain/);
  assert.match(source, /buildAuthorityRequestPanel/);
  assert.match(source, /resolveProfileAuthorityContext/);
  assert.match(source, /renderCommunityMyData/);
  assert.match(source, /Public progression/);
  assert.match(source, /Recent XP events/);
  assert.match(source, /Public economy and inventory/);
  assert.match(source, /Recent economy history/);
  assert.match(source, /Pending review/);
  assert.match(source, /openAuthModal:\s*ctx\.openAuthModal/);
});

test("public profile owner editor stays runtime-backed and uses canonical social assets", () => {
  const app = read("js/public-pages-app.js");
  const hub = read("js/public-data-hub.js");
  const css = read("css/public-shell.css");

  assert.match(hub, /key: "pickax"[\s\S]*label: "Pickax"[\s\S]*icon: "\/assets\/icons\/pickax\.svg"/);
  assert.match(hub, /key: "onlyfans"[\s\S]*label: "OnlyFans"[\s\S]*icon: "\/assets\/icons\/onlyfans\.svg"/);
  assert.match(app, /function openPublicProfileEditModal/);
  assert.match(app, /saveMyPublicProfile\(payload\)/);
  assert.match(app, /function validatePublicProfileEditorSocialUrl/);
  assert.match(app, /https:\/\/\$\{expectedHost\}\/yourhandle/);
  assert.match(app, /data-profile-edit-social/);
  assert.match(app, /profile-edit-open-button/);
  assert.match(app, /canEditProfile: canEdit/);
  assert.match(app, /if \(canEdit && \(error\?\.status === 401 \|\| error\?\.status === 403\)\)/);
  assert.match(css, /\.profile-edit-modal-backdrop/);
  assert.match(css, /\.profile-edit-media/);
  assert.match(css, /\.profile-edit-social-grid/);
});

test("public leaderboards route hydrates from authoritative progression API", () => {
  const app = read("js/public-pages-app.js");
  const css = read("css/public-shell.css");
  assert.match(app, /AUTH_PUBLIC_PROGRESSION_LEADERBOARD_URL = `\$\{AUTH_API_BASE\}\/api\/public\/progression\/leaderboard`/);
  assert.match(app, /AUTH_PUBLIC_PROGRESSION_SCOPES_URL = `\$\{AUTH_API_BASE\}\/api\/public\/progression\/scopes`/);
  assert.match(app, /AUTH_PUBLIC_PROGRESSION_PROFILE_URL = `\$\{AUTH_API_BASE\}\/api\/public\/progression\/profile`/);
  assert.match(app, /fetchPublicProgressionLeaderboard/);
  assert.match(app, /fetchPublicProgressionScopes/);
  assert.match(app, /fetchPublicProfileProgressionScopes/);
  assert.match(app, /endpoint\.searchParams\.set\("scope_key", scopeKey\)/);
  assert.match(app, /renderLeaderboards/);
  assert.match(app, /aliases: \["\/leaderboards", "\/leaderboards\/", "\/community\/leaderboard", "\/community\/leaderboard\/"\]/);
  assert.doesNotMatch(app, /renderLeaderboardsPlaceholder/);
  assert.match(app, /StreamSuites public leaderboards hub/);
  assert.match(app, /Global XP Leaderboards/);
  assert.match(app, /Current Board/);
  assert.match(app, /entry\?\.xp_total \?\? entry\?\.total_xp/);
  assert.match(app, /buildProgressionXpValue\(leaderboardXpTotal\(entry\), \{ compact: true, compactNumber: true \}\)/);
  assert.match(app, /placement_rank \|\| entry\?\.rank \|\| entry\?\.position/);
  assert.match(app, /buildProgressionLevelChip\(entry, \{ compact: true \}\)/);
  assert.match(app, /payload\?\.canonical_user_code/);
  assert.match(app, /authorityIdentity\?\.account_user_code/);
  assert.match(app, /function leaderboardHandle\(identity = \{\}\)/);
  assert.match(app, /identity\.public_slug[\s\S]*identity\.profile_slug[\s\S]*identity\.slug[\s\S]*identity\.handle[\s\S]*identity\.canonical_slug[\s\S]*profileUrlSlug/);
  assert.doesNotMatch(app.match(/function leaderboardHandle\(identity = \{\}\) \{[\s\S]*?return "";\n  \}/)?.[0] || "", /identity\.user_code/);
  assert.match(app, /return `@\$\{handle\}`/);
  assert.match(app, /fallback_public_identity_code/);
  assert.match(app, /function leaderboardProfileHref\(entry = \{\}\)/);
  assert.match(app, /identity\.public_slug \|\| identity\.publicSlug \|\| identity\.profile_slug \|\| identity\.profileSlug \|\| identity\.slug \|\| identity\.handle \|\| identity\.canonical_slug/);
  assert.match(app, /const link = create\("a", "dashboard-action progression-leaderboard-profile-link", "View profile"\)/);
  assert.match(app, /if \(slug\) return `\$\{CANONICAL_PROFILE_PREFIX\}\$\{encodeURIComponent\(slug\)\}`/);
  assert.match(app, /function safeLeaderboardProfileUrl\(value = ""\)/);
  assert.match(app, /const explicitHref = safeLeaderboardProfileUrl\(explicit\)/);
  assert.match(app, /if \(userCode\) return `\$\{CANONICAL_PROFILE_PREFIX\}\$\{encodeURIComponent\(userCode\)\}`/);
  assert.match(app, /identityCode && identityCode\.startsWith\("public-user"\)/);
  assert.match(app, /return `\$\{CANONICAL_PROFILE_PREFIX\}\$\{PROFILE_FALLBACK_SLUG\}`/);
  assert.match(app, /function buildLeaderboardDetail\(entry = \{\}\)/);
  assert.match(app, /row\.setAttribute\("aria-expanded", isExpanded \? "true" : "false"\)/);
  assert.match(app, /function toggleLeaderboardRow\(entry = \{\}, state = \{\}, isExpanded = false\)/);
  assert.match(app, /row\.addEventListener\("keydown"/);
  assert.match(app, /event\.key !== "Enter" && event\.key !== " "/);
  assert.match(app, /isInteractiveLeaderboardTarget\(event\.target\)/);
  assert.doesNotMatch(app, /"progression-leaderboard-expand", isExpanded \? "Hide details" : "Details"/);
  assert.doesNotMatch(app, /"Actions"\]/);
  assert.match(app, /create\("button", "progression-leaderboard-chevron"\)/);
  assert.match(app, /chevron\.type = "button"/);
  assert.match(app, /chevron\.addEventListener\("click"/);
  assert.match(app, /createIcon\(isExpanded \? UI_ICON_MAP\.minus : UI_ICON_MAP\.plus, "progression-leaderboard-chevron-icon"\)/);
  assert.doesNotMatch(app, /create\("span", "progression-leaderboard-chevron", isExpanded \? "Hide" : "Show"\)/);
  assert.match(app, /function filterLeaderboardRows\(rows = \[\], query = ""\)/);
  assert.match(app, /Search by name, @handle, level, or badge/);
  assert.match(app, /search\.className = "progression-leaderboard-search-input"/);
  assert.match(app, /leaderboard-scope-toolbar progression-leaderboard-controls/);
  assert.equal((app.match(/dataset\.scopeToolbar = "leaderboard"/g) || []).length, 1);
  assert.match(app, /controls\.dataset\.scopeToolbar = "leaderboard"/);
  assert.match(app, /leaderboard-scope-toolbar-controls/);
  assert.match(app, /scopeControl\.dataset\.scopeControl = "leaderboard"/);
  assert.match(app, /scopeControl\.dataset\.scopeMode = "global"/);
  assert.match(app, /Global leaderboard/);
  assert.match(app, /scopedProgressionScopeLabel\(state\.scopeMeta/);
  assert.match(app, /createScopedPlatformIcon\(scoped \? state\.scopeMeta : "global", "progression-leaderboard-scope-chip-icon"\)/);
  assert.match(app, /Channel/);
  assert.match(app, /scopeSelect\.disabled = !scoped \|\| \(!availableScopes\.length && !state\.scopeKey\)/);
  assert.match(app, /No channel scopes/);
  assert.match(app, /No channel scoped leaderboards found yet\./);
  assert.match(app, /Channel scoped leaderboards could not be loaded\./);
  assert.doesNotMatch(app, /progression-leaderboard-scope-control/);
  assert.doesNotMatch(app, /progression-leaderboard-scope-field-label/);
  assert.doesNotMatch(app, /Search channel scopes/);
  assert.doesNotMatch(app, /Leaderboard scope/);
  assert.doesNotMatch(app, /Global remains the default\. Channel scoped views show XP\/rank earned inside a creator\/channel context\./);
  assert.match(app, /renderLeaderboardScopeOptions\(scopeSelect, availableScopes/);
  assert.match(app, /readLeaderboardScopeFromUrl/);
  assert.match(app, /writeLeaderboardScopeToUrl\(cleanScope\)/);
  assert.match(app, /loadLeaderboard\(""\)/);
  assert.match(app, /loadLeaderboard\(nextScope\)/);
  assert.match(app, /fetchPublicProgressionScopes\(\)/);
  assert.match(app, /normalizeScopedProgressionRows\(rawRows\)/);
  assert.match(app, /No scoped XP rows were returned for this creator\/channel yet/);
  assert.match(app, /aliases: \["\/leaderboards", "\/leaderboards\/", "\/community\/leaderboard", "\/community\/leaderboard\/"\]/);
  assert.match(app, /kick: "\/assets\/icons\/kick\.svg"/);
  assert.match(app, /youtube: "\/assets\/icons\/youtube\.svg"/);
  assert.match(app, /rumble: "\/assets\/icons\/rumble\.svg"/);
  assert.match(app, /twitch: "\/assets\/icons\/twitch\.svg"/);
  assert.match(app, /pilled: "\/assets\/icons\/pilled\.svg"/);
  assert.match(app, /global: "\/assets\/icons\/ui\/globe\.svg"/);
  assert.match(app, /unknown: "\/assets\/icons\/ui\/cast\.svg"/);
  assert.match(app, /state\.page = 1/);
  assert.match(app, /const LEADERBOARD_PAGE_SIZE = 20/);
  assert.match(app, /const pageRows = filteredRows\.slice\(pageStart, pageStart \+ LEADERBOARD_PAGE_SIZE\)/);
  assert.match(app, /paginationHost\.appendChild\(buildLeaderboardPagination\(state, totalPages\)\)/);
  assert.match(app, /progressionLevelPresentation\(entry\)/);
  assert.match(app, /addStat\("Rank", `#\$\{formatNumber/);
  assert.match(app, /function formatCompactNumber\(value\)/);
  assert.match(app, /1_000_000[\s\S]*suffix: "M"/);
  assert.match(app, /1_000_000_000[\s\S]*suffix: "B"/);
  assert.match(app, /1_000_000_000_000[\s\S]*suffix: "T"/);
  assert.match(app, /stats\.appendChild\(walletStat\);\s*stats\.appendChild\(buildLeaderboardLevelCard\(entry\)\)/);
  assert.match(app, /applyProfileCurrentLevelCardTheme\(item, entry\)/);
  assert.match(app, /walletStat\.append\(create\("dt", "", "Wallet"\)\)/);
  assert.match(app, /function leaderboardInventoryItems\(entry = \{\}\)/);
  assert.match(app, /function buildLeaderboardInventoryOverview\(entry = \{\}\)/);
  assert.match(app, /detail\.append\(summary, stats, buildLeaderboardInventoryOverview\(entry\)\)/);
  assert.match(app, /entry\?\.economy_summary\?\.inventory/);
  assert.match(app, /entry\?\.inventory_summary/);
  assert.match(app, /progression-leaderboard-inventory-meta/);
  assert.match(app, /\[definition\.category, definition\.rarity\]\.filter\(Boolean\)\.join\(" • "\)/);
  assert.match(app, /progression-leaderboard-inventory-overflow/);
  assert.match(app, /return buildEconomyBalanceValue\(wallet, \{ compactNumber: true \}\)/);
  assert.doesNotMatch(app, /This public identity is ranked from authoritative StreamSuites XP only/);
  assert.match(app, /function normalizeLeaderboardWalletFields\(source = \{\}\)/);
  assert.match(app, /entry\?\.wallet_summary/);
  assert.match(app, /entry\?\.economy_summary/);
  assert.match(app, /candidate\.balance_total_credits/);
  assert.match(app, /candidate\.cash_balance_credits/);
  assert.match(app, /candidate\.held_value_credits/);
  assert.match(app, /candidate\.currency_unit_plural_label/);
  assert.match(app, /value:\s*`\$\{formatCompactNumber\(stats\.lifetimeXp\)\} XP`/);
  assert.match(app, /const walletCurrency = wallets\[0\] \|\| \{\}/);
  assert.match(app, /buildEconomyBalanceValue\(\{ \.\.\.stats\.walletCurrency, balance_total_credits: stats\.walletTotal \}, \{ compact: true, compactNumber: true \}\)/);
  assert.doesNotMatch(app, /addStat\("Rank", level\.label/);
  assert.match(app, /LEADERBOARD_PLACEMENT_ASSETS = Object\.freeze/);
  assert.match(app, /1: "\/assets\/games\/lb-first\.webp"/);
  assert.match(app, /2: "\/assets\/games\/lb-second\.webp"/);
  assert.match(app, /3: "\/assets\/games\/lb-third\.webp"/);
  assert.match(app, /function computeLeaderboardTiePlacements\(rows = \[\]\)/);
  assert.match(app, /currentPlacement = index \+ 1/);
  assert.match(app, /tie_placement_rank: currentPlacement/);
  assert.match(app, /function renderLeaderboardPodium\(host, rows = \[\]\)/);
  assert.match(app, /const topRows = rows\.filter/);
  assert.match(app, /placement >= 1 && placement <= 3/);
  assert.match(app, /renderLeaderboardPodium\(podium, state\.rows\)/);
  assert.match(app, /ss-lb-podium-card--first/);
  assert.match(app, /create\("span", "ss-lb-premium-shimmer"\)/);
  assert.match(app, /pageRows\.forEach\(\(entry\) => list\.appendChild\(buildLeaderboardRow\(entry, state\)\)\)/);
  assert.match(app, /renderSignedOutStanding\(standingHost, openAuthModal\)/);
  assert.match(app, /renderSignedInStanding\(standingHost, standingEntry, progressionPayload, economyPayload, authState \|\| \{\}\)/);
  const standingBlock = app.match(/function renderSignedInStanding\(host, entry = null, progressionPayload = \{\}, economyPayload = \{\}, authState = \{\}\) \{[\s\S]*?host\.appendChild\(card\);\n  \}/)?.[0] || "";
  assert.match(standingBlock, /const authSlug = getCanonicalProfileSlug\(authState, ""\)/);
  assert.doesNotMatch(standingBlock, /buildProfileHref\(authState\)/);
  assert.match(standingBlock, /buildEconomyBalanceValue\(wallet, \{ compact: true, compactNumber: true, standing: true \}\)/);
  assert.match(app, /renderLeaderboardGallery\(gallery, availableScopes/);
  assert.match(app, /Creator and channel boards/);
  assert.match(app, /Available boards come from the Runtime\/Auth scoped progression contract/);
  assert.match(app, /progression-leaderboard-gallery-action/);
  assert.match(app, /loadLeaderboard\(scopeKey \|\| ""\)/);
  assert.doesNotMatch(app, /Creator-defined boards preview/);
  assert.doesNotMatch(app, /progression-leaderboard-future-tab/);
  assert.match(css, /\.progression-leaderboard-row/);
  assert.match(css, /\.progression-leaderboard-row--top-1/);
  assert.match(css, /\.progression-leaderboard-row--top:hover\s*\{[\s\S]*--leaderboard-placement-color/);
  assert.match(css, /\.progression-leaderboard-hero/);
  assert.match(css, /\.progression-leaderboard-stat-grid/);
  assert.match(css, /\.progression-leaderboard-podium/);
  assert.match(css, /\.progression-leaderboard-podium-card--1/);
  assert.match(css, /\.progression-leaderboard-standing-card/);
  assert.match(css, /\.progression-leaderboard-standing-stats \.economy-balance-value--standing\s*\{[\s\S]*font-size:\s*inherit/);
  assert.match(css, /\.progression-leaderboard-detail-stat \.economy-balance-value\s*\{[\s\S]*font-size:\s*inherit/);
  assert.match(css, /\.progression-leaderboard-table-header/);
  assert.match(css, /--progression-leaderboard-row-grid/);
  assert.match(css, /\.progression-leaderboard-header-profile\s*\{[\s\S]*grid-column:\s*2 \/ 4/);
  assert.match(css, /\.progression-leaderboard-row-main\s*\{[\s\S]*grid-template-columns:\s*var\(--progression-leaderboard-row-grid\)/);
  assert.match(css, /\.progression-leaderboard-chevron-icon/);
  assert.match(css, /\.progression-leaderboard-pagination/);
  assert.match(app, /progression-leaderboard-page-button progression-leaderboard-page-button--/);
  assert.match(css, /\.progression-leaderboard-gallery-card/);
  assert.match(css, /\.progression-leaderboard-medallion/);
  assert.match(css, /\.progression-leaderboard-level-card/);
  assert.match(css, /\.progression-leaderboard-detail\s*\{[\s\S]*grid-template-columns:\s*minmax\(180px, 220px\) minmax\(0, 1fr\)/);
  assert.match(css, /\.progression-leaderboard-detail-stats\s*\{[\s\S]*grid-template-columns:\s*repeat\(4, minmax\(0, 1fr\)\)/);
  assert.match(css, /\.progression-leaderboard-detail-stat\s*\{[\s\S]*min-height:\s*74px/);
  assert.match(css, /\.progression-leaderboard-level-card dd\s*\{[\s\S]*align-items:\s*center/);
  assert.match(css, /\.progression-leaderboard-profile-link\s*\{[\s\S]*width:\s*min\(100%, 174px\)/);
  assert.match(css, /\.progression-leaderboard-detail-actions/);
  assert.match(css, /\.progression-leaderboard-inventory-overview/);
  assert.match(css, /\.progression-leaderboard-inventory-rail/);
  assert.match(css, /\.progression-leaderboard-inventory-body/);
  assert.match(css, /\.progression-leaderboard-inventory-meta/);
  assert.match(css, /\.progression-board\.dashboard-card/);
  assert.match(css, /\.progression-leaderboard-detail/);
  assert.match(css, /\.leaderboard-scope-toolbar/);
  assert.match(css, /grid-template-columns:\s*minmax\(260px, 1fr\) auto minmax\(220px, 320px\) minmax\(112px, 180px\) auto/);
  assert.match(css, /\.leaderboard-scope-toolbar-controls\s*\{\s*display:\s*contents/);
  assert.match(css, /\.progression-leaderboard-search,[\s\S]*\.progression-leaderboard-scope-select,[\s\S]*\.progression-leaderboard-scope-feedback\s*\{[\s\S]*min-width:\s*0/);
  assert.match(css, /\.progression-leaderboard-search input/);
  assert.match(css, /\.progression-leaderboard-search input::placeholder/);
  assert.match(css, /\.progression-leaderboard-scope-chip/);
  assert.match(css, /\.progression-leaderboard-scope-mode/);
  assert.match(css, /\.progression-leaderboard-scope-feedback/);
  assert.match(css, /\.progression-leaderboard-scope-search input/);
  assert.match(css, /\.progression-leaderboard-scope-select select/);
  assert.match(css, /\.progression-leaderboard-scope-select select:disabled/);
  assert.match(css, /\.progression-leaderboard-scope-chip-icon/);
  assert.match(css, /\.progression-leaderboard-scope-chip-icon\s*\{[\s\S]*width:\s*14px[\s\S]*background-color:\s*currentColor[\s\S]*mask-image:\s*var\(--icon-mask\)/);
  assert.doesNotMatch(css, /\.progression-leaderboard-scope-control/);
  assert.doesNotMatch(css, /\.progression-leaderboard-scope-label/);
  assert.doesNotMatch(css, /\.progression-leaderboard-scope-field-label/);
  assert.doesNotMatch(css, /\.progression-leaderboard-scope-note/);
  assert.match(css, /\.progression-leaderboard-gallery-action/);
  assert.match(css, /\.ss-lb-premium-shimmer/);
  assert.match(css, /@keyframes ss-lb-premium-shimmer/);
  assert.match(css, /prefers-reduced-motion:\s*reduce[\s\S]*\.ss-lb-premium-shimmer::before/);
  assert.match(css, /\.progression-level-chip/);
  assert.match(css, /\.progression-xp-icon/);
});

test("public profile game section renders runtime progression and economy authority summaries", () => {
  const app = read("js/public-pages-app.js");
  const css = read("css/public-shell.css");
  const profileSection = app.match(/function buildProfileGameCompetitionSection\(profile = null, options = \{\}\) \{[\s\S]*?return details;\n  \}/)?.[0] || "";
  const scopedProfileSection = app.match(/function buildProfileScopedProgressionSection\(profile = null\) \{[\s\S]*?return section;\n  \}/)?.[0] || "";
  assert.ok(profileSection, "profile progression section should exist");
  assert.ok(scopedProfileSection, "profile scoped progression section should exist");
  assert.match(app, /payload\?\.progression && typeof payload\.progression === "object"/);
  assert.match(app, /payload\?\.economy && typeof payload\.economy === "object"/);
  assert.match(app, /Array\.isArray\(payload\?\.inventory\)/);
  assert.match(app, /ECONOMY_CURRENCY_SYMBOL_PATH = "\/assets\/games\/currencyunit\.svg"/);
  assert.match(app, /function buildEconomyDenominationBreakdown\(wallet = \{\}\)/);
  assert.match(app, /function buildEconomyBreakdownList\(rows = \[\], emptyText = "No entries available yet\.", className = ""\)/);
  assert.match(app, /economy-breakdown-meta/);
  assert.match(app, /meta \? `\[\$\{meta\}\]` : ""/);
  assert.match(app, /wallet\.denomination_breakdown\.filter/);
  assert.match(app, /item\?\.should_display \|\| item\?\.always_show_in_balance \|\| Number\(item\?\.count \|\| 0\) > 0/);
  assert.match(app, /icon\.style\.setProperty\("--economy-currency-symbol"/);
  assert.match(app, /fullColorIcon/);
  assert.match(profileSection, /progression\.xp_total \?\? progression\.total_xp/);
  assert.match(profileSection, /const scopedRows = normalizeScopedProgressionRows/);
  assert.match(profileSection, /scopeWrap\.dataset\.profileScopeSelector = "compact"/);
  assert.match(profileSection, /profile-game-scope-select-input/);
  assert.match(profileSection, /details\.dataset\.profileProgressionMode = scoped \? "scoped" : "global"/);
  assert.match(profileSection, /panel\.dataset\.profileProgressionMode = scoped \? "scoped" : "global"/);
  assert.match(profileSection, /Current XP \/ Scoped rank/);
  assert.match(profileSection, /Scoped level/);
  assert.match(profileSection, /Messages/);
  assert.match(profileSection, /No scoped wallet data yet/);
  assert.match(profileSection, /No scoped inventory data yet/);
  assert.match(profileSection, /buildEconomyBalanceValue\(economy \|\| \{\}, \{ prominent: true, fullColorIcon: true, showCashComponent: true \}\)/);
  assert.match(profileSection, /buildEconomyDenominationBreakdown\(economy \|\| \{\}\)/);
  assert.match(profileSection, /buildInventorySummaryList\(displayInventory\)/);
  assert.match(profileSection, /buildPublicValueItemExchangePanel\(exchangeableItems\)/);
  assert.match(profileSection, /options\.canEdit/);
  assert.match(profileSection, /buildProgressionXpValue\(sourceXpTotal, \{ prominent: true \}\)/);
  assert.match(profileSection, /buildProgressionLevelChip\(source, \{ prominent: true \}\)/);
  assert.match(app, /function publicLevelBannerImagePath\(presentation = \{\}\)/);
  assert.match(app, /PUBLIC_LEVEL_BANNER_ASSET_SLUGS = new Set/);
  assert.match(app, /\/assets\/backgrounds\/lvlbanner-\$\{slug\}\.webp/);
  assert.match(profileSection, /profile-game-preview-card--featured profile-game-preview-card--current-level/);
  assert.match(profileSection, /applyProfileCurrentLevelCardTheme\(card, source\)/);
  assert.match(profileSection, /scoped \? "Current XP \/ Scoped rank" : "Current XP \/ Global rank"/);
  assert.match(profileSection, /buildProgressionGlobalRankValue\(progression, \{ prominent: true, emptyLabel: "Unranked" \}\)/);
  assert.match(profileSection, /LEADERBOARD_PLACEMENT_ASSETS\[sourcePlacementRank\]/);
  assert.match(profileSection, /Leaderboard placement is separate from/);
  assert.match(profileSection, /No global leaderboard placement has been returned for this identity yet/);
  assert.match(profileSection, /profile-game-preview-card--featured/);
  assert.match(profileSection, /profile-game-progress-meter/);
  assert.match(profileSection, /No level yet/);
  assert.doesNotMatch(profileSection, /value: progression \? buildProgressionRankChip\(progression, \{ compact: true \}\) : "Bronze"/);
  assert.match(profileSection, /XP, level, wallet balance, and inventory hydrate from runtime public authority/);
  assert.match(css, /\.progression-xp-value--prominent/);
  assert.match(css, /\.progression-global-rank-value--prominent/);
  assert.match(css, /\.economy-balance-value--prominent/);
  assert.match(css, /\.economy-balance-icon--full-color/);
  assert.match(css, /\.profile-game-xp-rank-combo--top-1/);
  assert.match(css, /\.profile-game-xp-rank-combo--top-2/);
  assert.match(css, /\.profile-game-xp-rank-combo--top-3/);
  assert.match(css, /\.profile-game-xp-rank-placement-icon/);
  assert.match(css, /\.profile-game-scope-compact/);
  assert.match(css, /\.profile-game-scope-select-input/);
  assert.match(app, /1: "\/assets\/games\/lb-first\.webp"/);
  assert.match(app, /2: "\/assets\/games\/lb-second\.webp"/);
  assert.match(app, /3: "\/assets\/games\/lb-third\.webp"/);
  assert.match(css, /\.progression-level-chip--prominent/);
  assert.match(css, /\.profile-game-preview-card--featured/);
  assert.match(css, /\.profile-game-preview-card--current-level/);
  assert.match(css, /--profile-current-level-color/);
  assert.match(css, /--profile-current-level-banner-image/);
  assert.match(css, /var\(--profile-current-level-banner-image\) right center \/ cover no-repeat/);
  assert.match(css, /\.profile-game-preview-card--current-level::before\s*\{[\s\S]*mask-image:\s*linear-gradient/);
  assert.match(css, /\.profile-game-preview-card--current-level\.has-level-banner::before\s*\{[\s\S]*opacity:\s*0\.62/);
  assert.match(css, /\.profile-game-preview-card--breakdown,[\s\S]*\.profile-game-preview-card--progress\s*\{[\s\S]*grid-column:\s*span 3/);
  assert.match(profileSection, /profile-game-preview-card--breakdown profile-game-preview-card--balance/);
  assert.match(profileSection, /profile-game-preview-card--breakdown profile-game-preview-card--inventory/);
  assert.match(css, /\.profile-game-inventory-stack/);
  assert.match(app, /buildProfileGameCompetitionSection\(profile, \{ canEdit \}\)/);
  assert.match(app, /function buildProfileScopedProgressionSection\(profile = null\)/);
  assert.match(app, /profile\?\.scopedProgression \|\| profile\?\.scoped_progression/);
  assert.doesNotMatch(app, /if \(!rows\.length\) return null/);
  assert.match(app, /hydrateProfileScopedProgression\(profile, profileCode\)/);
  assert.match(app, /"VIEW BOARD"/);
  assert.match(app, /scopedLeaderboardHref\(row\.scope_key\)/);
  assert.match(profileSection, /buildInventorySummaryList\(scopedInventory\)/);
  assert.match(profileSection, /leaderboardHasInventoryPayload\(selectedRow\)/);
  assert.match(profileSection, /scopedInventoryAvailable \? "Empty" : "Unavailable"/);
  assert.match(css, /\.profile-scoped-progression-section/);
  assert.match(scopedProfileSection, /section\.dataset\.profileChannelStats = "present"/);
  assert.doesNotMatch(scopedProfileSection, /Global Stats/);
  assert.doesNotMatch(scopedProfileSection, /Channel Stats/);
  assert.match(scopedProfileSection, /No channel-scoped XP has been recorded for this profile yet\./);
  assert.match(scopedProfileSection, /Channel scoped progression could not be loaded\./);
  assert.match(scopedProfileSection, /section\.dataset\.scopedBoardsList = "profile"/);
  assert.match(scopedProfileSection, /profile-scoped-progression-list/);
  assert.match(scopedProfileSection, /profile-scoped-progression-table-head/);
  assert.match(app, /"VIEW BOARD"/);
  assert.match(css, /\.profile-scoped-progression-row/);
  assert.match(css, /\.profile-scoped-progression-table-head/);
  assert.match(css, /\.profile-scoped-progression-empty/);
  assert.doesNotMatch(app, /profile-scoped-progression-tabs/);
});

test("public scoped platform icons and stable latest stream layout are pinned", () => {
  const app = read("js/public-pages-app.js");
  const css = read("css/public-shell.css");
  assert.match(app, /SCOPED_PLATFORM_ICON_MAP = Object\.freeze/);
  ["kick", "youtube", "rumble", "twitch", "pilled", "global", "unknown"].forEach((key) => {
    assert.match(app, new RegExp(`${key}:`));
  });
  assert.match(app, /function createScopedPlatformIcon/);
  assert.match(app, /function createScopedPlatformBrandIcon/);
  assert.match(app, /function createScopedPlatformChip/);
  assert.match(app, /createScopedPlatformBrandIcon\(source, "scoped-platform-chip-icon"\)/);
  assert.match(css, /img\.profile-game-scope-chip-icon,[\s\S]*img\.scoped-platform-chip-icon\s*\{[\s\S]*-webkit-mask:\s*none/);
  assert.match(app, /function buildProfileCollapsibleToggle\(details, className = "profile-collapsible-toggle"\)/);
  assert.match(app, /label\.textContent = details\.open \? "Collapse" : "Expand"/);
  assert.match(app, /summary\.append\(action, meta, buildProfileCollapsibleToggle\(details\)\)/);
  assert.match(app, /summary\.append\(action, scopeWrap, buildProfileCollapsibleToggle\(details\)\)/);
  assert.doesNotMatch(app, /hasUsableStream \? stream\?\.platformLabel : "No data available"/);
  assert.doesNotMatch(app, /hasUsableStream \? \(stream\?\.isLive \? "Current live" : "Featured source"\) : "Expand for details"/);
  assert.match(css, /\.profile-collapsible-toggle\s*\{[\s\S]*border-radius:\s*999px/);
  assert.match(app, /card\.dataset\.latestStreamLayout = "stable"/);
  assert.match(app, /row\.dataset\.previousStreamsTray = "true"/);
  assert.match(app, /realRows = recent\.filter[\s\S]*\.slice\(0, 6\)/);
  assert.match(css, /\.profile-latest-stream-card\s*\{[\s\S]*grid-template-columns:\s*minmax\(320px, 1\.18fr\) minmax\(0, 0\.82fr\)/);
  assert.match(css, /\.profile-latest-stream-thumbnails\s*\{[\s\S]*grid-template-columns:\s*repeat\(6, minmax\(0, 1fr\)\)/);
  assert.match(css, /\.profile-latest-stream-body\s*\{[\s\S]*align-content:\s*start/);
  assert.match(css, /\.profile-latest-stream-body h3\s*\{[\s\S]*overflow-wrap:\s*anywhere/);
});

test("public profile overview table uses the same runtime progression summary as games", () => {
  const app = read("js/public-pages-app.js");
  const overviewSection = app.match(/function buildProfileOverviewPanel\(profile, artifacts, helpers\) \{[\s\S]*?return section;\n  \}/)?.[0] || "";
  assert.ok(overviewSection, "profile overview section should exist");
  assert.match(overviewSection, /const progression = profile\?\.progression && typeof profile\.progression === "object" \? profile\.progression : null/);
  assert.match(overviewSection, /const economy = profile\?\.economy && typeof profile\.economy === "object" \? profile\.economy : null/);
  assert.match(overviewSection, /progression\.xp_total \?\? progression\.total_xp \?\? 0/);
  assert.match(overviewSection, /buildProgressionXpValue\(progression\.xp_total \?\? progression\.total_xp \?\? 0, \{ compact: true \}\)/);
  assert.match(overviewSection, /buildProgressionLevelChip\(progression, \{ compact: true \}\)/);
  assert.match(overviewSection, /buildProgressionGlobalRankValue\(progression, \{ compact: true, emptyLabel: "Unranked" \}\)/);
  assert.match(overviewSection, /addRow\("XP", overviewXpValue, !progression\)/);
  assert.match(overviewSection, /addRow\("Level", overviewLevelValue, !progression\)/);
  assert.match(overviewSection, /addRow\("Global Rank", overviewGlobalRankValue, !progression\)/);
  assert.match(overviewSection, /addRow\("Balance", economy \? buildEconomyBalanceValue\(economy, \{ compact: true \}\) : "Starting", false\)/);
  assert.match(overviewSection, /addRow\("Inventory", displayInventory\.length \? `\$\{formatNumber\(displayInventory\.length\)\} item type/);
  assert.doesNotMatch(overviewSection, /addRow\("XP", "Pending", true\)/);
  assert.doesNotMatch(overviewSection, /addRow\("Rank", "Pending", true\)/);
});

test("public level chips include restrained hover sheen without changing compact consumers", () => {
  const css = read("css/public-shell.css");

  assert.match(css, /\.progression-level-chip::before,[\s\S]*\.progression-rank-chip::before\s*\{/);
  assert.match(css, /\.progression-level-chip:hover::before,[\s\S]*\.progression-rank-chip:focus-visible::before\s*\{[\s\S]*animation:\s*progression-rank-chip-sheen 3\.2s/);
  assert.match(css, /@keyframes progression-rank-chip-sheen/);
  assert.match(css, /prefers-reduced-motion:\s*reduce[\s\S]*\.progression-rank-chip::before/);
  assert.match(css, /\.progression-level-chip--compact,[\s\S]*\.economy-balance-value--compact\s*\{[\s\S]*font-size:\s*12px/);
  assert.match(css, /\.progression-level-chip--compact \.progression-level-chip-icon,[\s\S]*\.economy-balance-value--compact \.economy-balance-icon\s*\{[\s\S]*width:\s*16px/);
  assert.match(css, /\.economy-balance-icon\s*\{[\s\S]*mask:\s*var\(--economy-currency-symbol\) center \/ contain no-repeat/);
  assert.match(css, /\.economy-denomination-breakdown\s*\{/);
  assert.match(css, /\.economy-breakdown-icon,[\s\S]*\.economy-denomination-chip img,[\s\S]*\.inventory-summary-icon\s*\{[\s\S]*object-fit:\s*contain/);
});

test("public economy rendering keeps denominations separate from inventory rows", () => {
  const app = read("js/public-pages-app.js");
  const css = read("css/public-shell.css");

  assert.match(app, /currency_unit_label \|\| "Credit"/);
  assert.match(app, /currency_unit_plural_label \|\| `\$\{singular\}s`/);
  assert.match(app, /walletOrValue\.balance_total_credits \?\? walletOrValue\.balance_current/);
  assert.match(app, /function resolveEconomyCashComponent\(wallet = \{\}, totalValue = 0\)/);
  assert.match(app, /options\.showCashComponent && cashValue !== null/);
  assert.match(app, /economy-balance-cash-component/);
  assert.match(app, /walletCard\.appendChild\(buildEconomyDenominationBreakdown\(wallet\)\)/);
  assert.match(app, /icon\.src = economyAssetPath\("\/assets\/games\/sscurrency\.webp"\)/);
  assert.match(app, /function isWalletDenominationInventoryItem\(item = \{\}\)/);
  assert.match(app, /\["currency\.coin", "currency\.bank_token"\]\.includes\(itemCode\)/);
  assert.doesNotMatch(app, /metadata\.system_asset_type === "economy_denomination"/);
  assert.match(app, /return Number\(item\?\.quantity \|\| 0\) > 0 && !isWalletDenominationInventoryItem\(item\)/);
  assert.match(app, /const displayInventory = inventory\.filter\(\(item\) => !isWalletDenominationInventoryItem\(item\)\)/);
  assert.match(app, /"currency\.gem\.green"/);
  assert.match(app, /"currency\.gem\.red"/);
  assert.match(app, /"currency\.gem\.blue"/);
  assert.match(app, /"currency\.diamond"/);
  assert.match(app, /className: "inventory-summary-row"/);
  assert.match(app, /quantityPrefix: "x"/);
  assert.match(app, /row\.append\(icon, body, create\("strong", "economy-breakdown-quantity", `\$\{entry\.quantityPrefix \|\| ""\}\$\{formatNumber\(entry\.quantity \|\| 0\)\}`\)\)/);
  assert.match(app, /const exchangePanel = buildPublicValueItemExchangePanel\(exchangeableItems\)/);
  assert.match(app, /Gems and diamonds cannot be purchased directly/);
  assert.match(app, /body: JSON\.stringify\(\{[\s\S]*item_code: itemCode,[\s\S]*quantity,[\s\S]*reason_text: reasonText/);
  assert.match(css, /\.economy-breakdown-row,[\s\S]*\.economy-denomination-chip,[\s\S]*\.inventory-summary-row\s*\{[\s\S]*grid-template-columns:\s*24px minmax\(0, 1fr\) auto/);
  assert.match(css, /\.economy-breakdown-icon,[\s\S]*\.economy-denomination-chip img,[\s\S]*\.inventory-summary-icon\s*\{[\s\S]*width:\s*24px/);
  assert.match(css, /\.economy-balance-cash-component\s*\{/);
});

test("public profile progress meter uses animated electric blue fill", () => {
  const app = read("js/public-pages-app.js");
  const css = read("css/public-shell.css");

  assert.match(app, /fill\.style\.setProperty\("--profile-progress-target", `\$\{sourceProgressPercent\}%`\)/);
  assert.match(app, /profile-game-progress-meter profile-game-progress-meter--animated/);
  assert.match(app, /profile-game-progress-meter-fill profile-game-progress-meter-fill--electric/);
  assert.match(css, /\.profile-game-progress-meter-fill\s*\{[\s\S]*linear-gradient\(90deg, #0487ff 0%, #18c3ff 52%, #78ecff 100%\)/);
  assert.match(css, /animation:\s*profile-game-progress-fill 820ms/);
  assert.match(css, /\.profile-game-preview-card--progress:hover \.profile-game-progress-meter-fill\s*\{[\s\S]*animation:\s*profile-game-progress-refill 620ms/);
  assert.match(css, /@keyframes profile-game-progress-fill/);
  assert.match(css, /@keyframes profile-game-progress-refill/);
  assert.match(css, /prefers-reduced-motion:\s*reduce[\s\S]*profile-game-progress-meter-fill/);
});
