import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

const repoRoot = process.cwd();

function read(relativePath) {
  return fs.readFileSync(path.join(repoRoot, relativePath), "utf8");
}

test("public data hub hydrates wheels from the authoritative live API first and reuses them for scoreboard mode", () => {
  const source = read("js/public-data-hub.js");

  assert.match(source, /const WHEELS_API_PATH = "\/api\/public\/wheels";/);
  assert.match(source, /wheels:\s*\["\/shared\/state\/wheels\.json", "\/runtime\/exports\/wheels\.json", "\/data\/wheels\.json"\]/);
  assert.match(source, /async function loadLiveWheelPayload\(\)/);
  assert.match(source, /fetch\(`\$\{API_BASE\}\$\{WHEELS_API_PATH\}`/);
  assert.match(source, /const wheelsPayload = wheelsApiPayload && Array\.isArray\(wheelsApiPayload\.items\)/);
  assert.match(source, /mode: wheelsApiPayload && Array\.isArray\(wheelsApiPayload\.items\) \? "api" : "mirror"/);
  assert.match(source, /function normalizeWheel\(raw, index, profiles, authorityArtifacts = null, wheelService = null\)/);
  assert.match(source, /function buildScoreboardLensFromWheel\(wheel\)/);
  assert.match(source, /const rawWheelSet = raw\?\.wheel_set/);
  assert.match(source, /const activeWheel = normalizedChildren\.find\(\(wheel\) => wheel\.wheelId === requestedActiveWheelId\) \|\| normalizedChildren\[0\];/);
  assert.match(source, /wheelSet,/);
  assert.match(source, /activeWheel,/);
  assert.match(source, /activeWheelId: activeWheel\.wheelId/);
  assert.match(source, /stage_background_preset:/);
  assert.match(source, /stage_background_color:/);
  assert.match(source, /stage_background_image_url:/);
  assert.match(source, /effectiveWeight/);
  assert.match(source, /resolvedEntries \* resolvedWeight/);
  assert.match(source, /const wheelService = wheelsApiPayload\?\.wheel_service/);
  assert.match(source, /normalizeWheel\(item, index, profilesMap, authorityArtifacts, wheelService\)/);
  assert.match(source, /const scoreboards = sortByUpdated\(wheels\.map\(\(item\) => buildScoreboardLensFromWheel\(item\)\)\);/);
});

test("wheels library exposes portable formats, owned/public tabs, child cards, and truthful failure states", () => {
  const app = read("js/public-pages-app.js");
  const client = read("js/wheel-api-client.js");
  const css = read("css/public-shell.css");

  assert.match(app, /function renderWheelsLifecycle\(ctx\)/);
  assert.match(app, /New Wheel Set/);
  assert.match(app, /Add Wheel to Existing Set/);
  assert.match(app, /Stage \/ Wheel Set \(\.stg\)/);
  assert.match(app, /Individual Wheel \(\.swl\)/);
  assert.match(app, /My Library/);
  assert.match(app, /Public Gallery/);
  assert.match(app, /\?summary=1&limit=50&offset=0/);
  assert.match(app, /WHEEL_API\.requestCreator/);
  assert.match(client, /credentials: "include"/);
  assert.match(client, /return "https:\/\/api\.streamsuites\.app"/);
  assert.match(app, /Wheel editing requires the current Runtime wheel service/);
  assert.match(app, /This is a network or Runtime error, not an empty gallery/);
  assert.doesNotMatch(app, /Your public wheel sets are already shown under My Wheel Sets/);
  assert.doesNotMatch(app, /Open workspace|Open Stage/);
  assert.match(app, /function buildMiniWheelThumbnail\(wheel\)/);
  assert.match(app, /function buildWheelSetLibraryCard\(set, onIdentityUpdated = null\)/);
  assert.match(app, /function buildChildWheelLibraryCard\(set, wheel, onIdentityUpdated = null\)/);
  assert.match(app, /function openEditWheelSetModal\(set, onUpdated\)/);
  assert.match(app, /Edit Wheel Set details/);
  assert.match(app, /Save Wheel Set details/);
  assert.match(app, /WHEEL_API\.updateArtifact\(set\.artifactCode, \{ title, description:/);
  assert.match(app, /ownedLibrary\?\.updateIdentity\(update\)/);
  assert.match(app, /publicGallery\?\.updateIdentity\(update\)/);
  assert.match(app, /url\.searchParams\.set\("wheel", wheelId\)/);
  assert.match(app, /nextUrl\.search = window\.location\.search;/);
  assert.match(app, /nextUrl\.hash = window\.location\.hash;/);
  assert.match(app, /role", "tablist"/);
  assert.match(app, /starter_entrants/);
  assert.match(app, /stage_background_preset/);
  assert.match(app, /payloadText = await selected\.text\(\)/);
  assert.match(app, /navigateToCanonicalWheel\(payload, String\(imported\.wheel_id/);
  assert.match(app, /wheelRefreshDeferred/);
  assert.match(app, /document\.body\.classList\.contains\("wheel-editor-open"\)/);
  assert.match(app, /streamsuites:wheel-editor-closed/);
  assert.match(css, /\.wheel-gallery-hero/);
  assert.match(css, /\.wheel-lifecycle-modal/);
  assert.match(css, /body\.public-shell-page\.modal-open :is\(\.ss-status-widget-host, \[data-status-widget-host\]\)/);
  assert.match(css, /@media \(max-width: 760px\)/);
  assert.match(css, /\.wheel-library-grid/);
  assert.match(css, /grid-template-columns: repeat\(3, minmax\(0, 1fr\)\)/);
  assert.match(css, /data-public-appearance="light"/);
  assert.match(css, /:is\(\.wheel-gallery-actions, \.wheel-lifecycle-actions\) :is\(\.wheel-production-primary, \.wheel-production-secondary\)/);
  assert.match(css, /\.wheel-production-primary[\s\S]*background: var\(--ss-control-primary\)/);
  assert.match(css, /\.wheel-production-secondary:is\(:hover, :focus-visible\)[\s\S]*background: var\(--ss-control-themed-subtle\)/);
  assert.match(css, /\.wheel-gallery-actions \.wheel-create-menu > \.wheel-production-primary \{ width: 100%; \}/);
});

test("public wheels route preserves the shell and provides clean list/detail artifact routes", () => {
  const app = read("js/public-pages-app.js");
  const shell = read("js/public-shell.js");
  const listHtml = read("wheels.html");
  const detailHtml = read("wheels/detail.html");
  const leaderboardsHtml = read("leaderboards.html");
  const indexFn = read("functions/wheels/index.js");
  const detailFn = read("functions/wheels/[[artifact]].js");
  const stageHtml = read("wheels/stage.html");
  const workspace = read("js/wheel-workspace.js");
  const wheelClient = read("js/wheel-api-client.js");
  const workspaceCss = read("css/wheel-workspace.css");
  const leaderboardsFn = read("functions/leaderboards/index.js");
  const css = read("css/public-shell.css");

  assert.match(app, /scoreboards: "\/leaderboards"/);
  assert.match(app, /aliases: \["\/wheels", "\/wheels\/"\]/);
  assert.match(app, /path: "\/leaderboards\.html"/);
  assert.match(app, /render: renderLeaderboards/);
  assert.match(app, /"media-scoreboards": \{[\s\S]*activeHref: "\/leaderboards"[\s\S]*topbarLabel: "Leaderboards"[\s\S]*render: renderLeaderboards/);
  assert.match(app, /detailType: "wheels"/);
  assert.match(app, /prefix: "\/wheels\/", pageId: "detail-wheel", detailType: "wheels"/);
  assert.doesNotMatch(app, /config\.filtersCollapsed = false/);
  assert.match(app, /function applyDocumentTitle\(label, options = \{\}\)/);
  assert.match(app, /function findArtifactByIdentifier\(items, identifier\)/);
  assert.match(app, /entry\?\.routeKeys\) && entry\.routeKeys\.includes\(normalizedRequested\)/);
  assert.match(app, /function resolveDefaultSidebarState\(config\)/);
  assert.match(app, /return String\(config\.path \|\| ""\)\.includes\("\/detail\.html"\) \? "icon" : "";/);
  assert.match(app, /defaultSidebarState: resolveDefaultSidebarState\(currentConfig\)/);
  assert.match(app, /defaultSidebarState: resolveDefaultSidebarState\(nextConfig\)/);
  assert.match(app, /function buildWheelDetailMain\(item, config\)/);
  assert.match(app, /StreamSuitesWheelWorkspace/);
  assert.match(detailHtml, /wheel-workspace\.css/);
  assert.match(detailHtml, /wheel-workspace\.js/);
  assert.match(detailFn, /stageRoute/);
  assert.doesNotMatch(stageHtml, /public-shell\.js|status-widget\.js/);
  assert.match(app, /sharedWorkspace\.createWorkspace\(item/);
  assert.match(app, /workspace\._cleanupWheelDetail = workspace\._cleanupWheelWorkspace/);
  assert.doesNotMatch(app, /function aggregateWheelEntrants\(entries\)/);
  assert.match(workspace, /const sourceSet = item\?\.wheelSet/);
  assert.match(workspace, /item\?\.activeWheel \|\| item/);
  assert.match(workspace, /function weightedWinner\(entries, random = Math\.random\)/);
  assert.match(workspace, /dialog\.setAttribute\("aria-modal", "true"\)/);
  assert.match(workspace, /window\.matchMedia\?\.\("\(prefers-reduced-motion: reduce\)"\)/);
  assert.match(workspace, /function startWinnerCelebration\(canvas, overlay, wheel\)/);
  assert.match(workspace, /Array\.from\(\{ length: 190 \}/);
  assert.match(workspace, /const fireworks = \[\]/);
  assert.match(workspace, /wheel-celebration-layer/);
  assert.match(app, /const PUBLIC_WHEEL_EVENTS_URL = WHEEL_API\?\.publicEventsUrl/);
  assert.match(detailHtml, /wheel-api-client\.js/);
  assert.match(stageHtml, /wheel-api-client\.js/);
  assert.match(wheelClient, /publicEventsUrl: `\$\{apiBase\}\$\{PUBLIC_WHEELS_PATH\}\/events`/);
  assert.match(app, /function syncWheelLiveSubscription\(\)/);
  assert.match(app, /wheelEventSource = new EventSource\(PUBLIC_WHEEL_EVENTS_URL, \{ withCredentials: true \}\);/);
  assert.match(app, /wheelEventSource\.addEventListener\("wheel\.changed"/);
  assert.match(app, /refreshWheelDataFromAuthority\(\)\.catch\(\(\) => \{\}\);/);
  assert.match(app, /function toTitle\(value\)/);
  assert.match(app, /applyDocumentTitle\(item\.title \|\| item\.question \|\| config\.topbarLabel\)/);
  assert.match(app, /updateShell\?\.\(\{ topbarLabel: item\.title \|\| item\.question \|\| config\.topbarLabel, filtersCollapsed: true \}\)/);
  assert.match(workspace, /winnerLimit/);
  assert.match(workspace, /spin_owner_only/);
  assert.match(workspace, /center_image_url/);
  assert.match(workspace, /stage_background_preset/);
  assert.match(workspace, /stage_background_color/);
  assert.match(workspace, /stage_background_image_url/);
  assert.match(workspace, /shortlinkSlug/);
  assert.match(workspace, /slice_label_mode/);
  assert.match(workspace, /Re-spin/);
  assert.match(workspace, /Reset wheel/);
  assert.match(workspace, /function spinAll\(\)/);
  assert.match(workspace, /spinAllScheduledCount/);
  assert.match(workspace, /no backend winner history/);
  assert.match(workspace, /wheel_id: wheel\.wheelId/);
  assert.match(shell, /href: "\/wheels", label: "Wheels"/);
  assert.doesNotMatch(shell, /href: "\/scoreboards", label: "List Views"/);
  assert.match(shell, /href: "\/leaderboards", label: "Leaderboards", icon: "\/assets\/icons\/ui\/tablechart\.svg"/);
  assert.match(shell, /const cleanPrefixes = \["\/clips\/", "\/polls\/", "\/scores\/", "\/wheels\/", "\/leaderboards\/"\]/);
  assert.match(shell, /defaultSidebarState: ""/);
  assert.match(shell, /autoSidebarStateOverride = normalizeSidebarState\(options\.defaultSidebarState\)/);
  assert.match(shell, /if \(useAutoSidebarState\) \{/);
  assert.match(listHtml, /data-public-page="media-wheels"/);
  assert.match(detailHtml, /data-public-page="detail-wheel"/);
  assert.match(leaderboardsHtml, /data-public-page="media-leaderboards"/);
  assert.match(indexFn, /serveAssetPath\(context, "\/wheels\.html"\)/);
  assert.match(detailFn, /basePath: "\/wheels"/);
  assert.match(detailFn, /assetPath: stageRoute \? "\/wheels\/stage\.html" : "\/wheels\/detail\.html"/);
  assert.match(leaderboardsFn, /serveAssetPath\(context, "\/leaderboards\.html"\)/);
  assert.match(css, /\.wheel-spin-shell-premium/);
  assert.match(css, /\.wheel-live-selection/);
  assert.match(css, /\.wheel-owner-editor-panel/);
  assert.match(css, /\.wheel-scoreboard-table/);
  assert.match(css, /\.wheel-stage-assembly/);
  assert.match(css, /\.detail-main\.wheel-detail-main/);
  assert.match(css, /\.wheel-console-workspace/);
  assert.match(css, /\.wheel-arena-atmosphere/);
  assert.match(css, /\.wheel-stage-chassis/);
  assert.match(css, /\.wheel-console-tabs/);
  assert.match(css, /\.wheel-winner-overlay/);
  assert.match(css, /@media \(forced-colors: active\)/);
  assert.match(css, /\.wheel-hardware-pointer/);
  assert.match(css, /\.wheel-share-field/);
  assert.match(css, /\.wheel-entry-detail-color-chip/);
  assert.match(css, /\.wheel-owner-sound-row/);
  assert.match(workspaceCss, /\.wheel-workspace/);
  assert.match(workspaceCss, /\.wheel-grid/);
  assert.match(workspaceCss, /body\.wheel-stage-document/);
  assert.match(workspaceCss, /\.wheel-workspace--stage/);
  assert.match(workspaceCss, /@media \(prefers-reduced-motion: reduce\)/);
  assert.match(workspaceCss, /\.wheel-celebration-layer/);
});
